### ISSUE TITLE
v1.1.11 release is broken: missing dist/ folder

### ISSUE THREAD

**Issue by wereHamster** [mariotacke/redux-electron-ipc#11]
See https://unpkg.com/redux-electron-ipc@1.1.11/

**Comment by mariotacke** [comment]
Will take a look at this ASAP. Thanks for reporting!

**Comment by mariotacke** [comment]
Not exactly sure what happened but it looks like Travis CI started to clean up the working directory sometime after 1.1.10 and before 1.1.11 for deploys. I prevented this with https://github.com/mariotacke/redux-electron-ipc/commit/b6cf3eda14e115f0e59370b18db7ac8ed102b706.

Newest release (v1.1.12) contains proper files again.
- https://unpkg.com/redux-electron-ipc@1.1.12/
