### ISSUE TITLE
electron app with react

### ISSUE THREAD

**Issue by ernestchakhoyan** [mariotacke/redux-electron-ipc#13]
when i am importing send method from redux-electron-ipc, it trows  an error----require is not defined.
how can i solve it?

**Comment by mariotacke** [comment]
Can you give some more information about your project and show some sample code? I'd like to see the file where you import the library and your webpack/parcel/gulp config if you have one. `require` is a node construct, which version of node are you running? Are you transpiling your code for the browser window in your electron app?

**Comment by ernestchakhoyan** [comment]
Hi @mariotacke , thanks for your response. 
Let me explain, what i am trying to do. I am using electron and react. I want to send some data from my React component via ipcRenderer (electron method) to electron main  process, but when i am importing ipcRenderer from electron into react component and trying to run in web browser via yarn start it throws me an error 'require is not defined' , but when i run the same code via electron build , it works fine. 
After many researches i have read a lot that you can not use any electron methods in web,.

So how can i solve this issue? I want to have one source code which will work for both - electron and react (web ) app.

**Comment by mariotacke** [comment]
@ernestchakhoyan, your research is correct. You cannot use electron specific code in the browser. Electron itself wraps a browser but extends the sandbox which allows you to do thing such as require without transpiling. I suggest designing your modules electron agnostic which lets you port them more easily between the browser and electron.

If you have a any remaining `redux-electron-ipc` specific questions let me know.
