### ISSUE TITLE
Dispatching another event after "Pong"

### ISSUE THREAD

**Issue by yourfavorite** [mariotacke/redux-electron-ipc#3]
Hello, I hope its okay to ask for advice on implementation here.

In my app I load in an array of objects from a local data file from the Main process and when it is returned to the Renderer I update the state with the array of data. In my app UI, one of these array items must be active. 

In a different part of the state I have `selectedItem` which stores the id property from the object within the array. My question is, what would be the best way to default to a specific item in the Array, let's say the first one?

Since redux-electron-ipc calls an Action Creator upon returning the data, where should I dispatch another call to update the `selectedItem`? Should it happen in the Reducer of the Action Creator?

**Comment by mariotacke** [comment]
Absolutely okay to ask for advice here.

Assuming I understand your question correctly, I think you have two options here:
1. You can do it in a single event. The action that saves the data on the state can also be used to initialize your selected item.
2. You can dispatch a `thunk` with two dispatches, one to save your data on the state, and another to select the current item.

Personally, I would go with 1, as it is conceptually the simplest.

Feel free to paste your solution or sample code so we can discuss.

**Comment by yourfavorite** [comment]
Thanks for the advice! (and the awesome module)

Still kind of new with all of this so after unsuccessfully doing some research on the methods you proposed, I ended up using componentWillReceiveProps and setting the default that way. Hopefully  this is an okay way to handle things :D

**Comment by mariotacke** [comment]
Absolutely. Whatever works. Please close the issue if you have no other questions. Thanks!
