### ISSUE TITLE
Module doesn't work in packaged app?

### ISSUE THREAD

**Issue by yourfavorite** [mariotacke/redux-electron-ipc#4]
I'm currently using [electron-react-boilerplate](https://github.com/chentsulin/electron-react-boilerplate) which uses webpack. My code runs fine when in dev (`npm run dev`) but when I package via electron-packager, redux-electron-ipc quits working. 

To confirm this I have replaced an redux-electron-ipc send with a plain ipcRenderer send and the main process received the event. Similarly when the main process sends back, redux-electron-ipc does not recognize the event and nothing happens. 

I have tried adding redux-electron-ipc to webpack externals but that didn't seem to help.

**Comment by mariotacke** [comment]
Can you copy some relevant code that shows how you are using the middleware? In particular, I'd like to see how you wire it up, your ipc event setup and an ipcMain method in your main.

**Comment by yourfavorite** [comment]
Ah man, sorry I bothered you on this one. I guess I was just too tired to figure this out on my own last night. As I went to copy and paste code here for you this morning. I realized that I forgot to add the createIpc call to my configureStore.production.js file...

I updated my production store file and all is well. Again, sorry for the mixup. Thanks for this great little module :D

**Comment by mariotacke** [comment]
No worries, the devil is in the details ;) Glad you got it figured out!
