### ISSUE TITLE
Unable to receive IPC event.

### ISSUE THREAD

**Issue by rjzheng** [mariotacke/redux-electron-ipc#6]
I am writing an Electron program that listens to a renderer's ipcRenderer event. I followed the example code from the README:
```js
const ipc = createIpc({
  'channel to listen to': () => {
    return {
      action: 'IPC_RESPONSE_ACTION',
      ... optional mapping of arguments ...
    }
  }
  ...
});

const store = createStore(exampleReducer, applyMiddleware(ipc));
```

I noticed that 'action' should be switched to 'type', and I've tried both and they both don't work. In my renderer.js, I have a pretty standard 
`ipcRenderer.send('IPC_RESPONSE_ACTION', 'test')`
Nothing was received in my reducers, nor did anything happen when I tried console.log received actions.

Currently I use a workaround where I send an event using the send API, and get a response from renderer.js's return.

**Comment by mariotacke** [comment]
You are absolutely right, the docs mistakenly specify `action` instead of `type` in the action creator payload. Can you paste your relevant code for: `createIpc`, your action creator, and where in your main.js (electron side) you call the `event.sender.send` or `window.webContents.send`?

**Comment by mariotacke** [comment]
@rjzheng, do you still have this problem?

**Comment by rjzheng** [comment]
I would still have this problem, but I fixed it by calling an external javascript function. Before this, I did a work around by sending a request from redux and replying w a response from my main.js in Electron.

**Comment by mariotacke** [comment]
Okay, great. Do you still want to debug your original approach or can we close this issue?

**Comment by rjzheng** [comment]
We can close this issue, if people need help in the future maybe they can refer back to here and we can help them.
