### ISSUE TITLE
action-create .catch handling

### ISSUE THREAD

**Issue by mtompkins** [mariotacke/redux-electron-ipc#7]
Thanks for sharing your work. A quick question please ...

Currently I have a `sequelize` promise call and I parse the outcome in my action-creator as follows:

```
...
return (dispatch: *) => {
    dispatch({ type: `${actionType}_PENDING` });
    sequelizeQry(qryName)
      .then((payload) => dispatch({
        type: `${actionType}_FULFILLED`,
        payload
      }))
      .catch(err =>
        // Dispatch the error action with error information
        dispatch({
          type: `${actionType}_REJECTED`,
          error: err
        })
      );
  };
...
```
thereby dispatching an ERROR action on an API failure. As your approach maps directly to an action-creator by channel name (i.e. `'pong': pongActionCreator, // receive a message`) do you have a recommended approach in handling failures from the main thread back to the renderer?

Many thanks

**Comment by mariotacke** [comment]
Hi, if I understand correctly, you are trying to send a message from your `ipcMain` to the `ipcRenderer`? The code you posted is your window/renderer?

You should be able to just register an event handler for your message from `ipcMain` in the `createIpc` call. 

Can you post some more supporting code of how you wired `ipcMain` and your renderer up?

**Comment by mtompkins** [comment]
Hi & Thanks for the response. The code above is currently the call to a `sequelize` promise and lives now (incorrectly) in the renderer thread and will reside, as any database connection, properly in the main thread. To accomplish this, my intent is to use your IPC wrapper (r-e-i) and make a call using the named channel. The promise in the main thread will have a response from the API with either a payload of data as an object if successful or an error object if not. 

You r-e-i, as I understand it, has no exposed logic to handle an error return, so in my case it will return any resolved promise to the mapped action-creator. A failure should not be passed to the same action-creator as a successful one. The are logically different.

To that end, I'm not asking about how to handle the connection from renderer to main, I'm asking how to handle a failed function return to the API as you've "hardcoded" the result to a specific action creator. 

In a perfect world, your wrapper would look a little more like this (in prototype form):

```
// register an action creator to an ipc channel (key/channel, value/action creator)
const ipc = createIpc({
  'pong': {pongActionCreator  // on success
              pongErrActionCreate} // on error
  ...
});

```

Unfortunately, I haven't added code to show as this question is a large influence on how I go about it.

**Comment by mariotacke** [comment]
IPC events do not contain an "error" callback as you might be familiar with from regular node.js code. IPC events just like any other events are one-way (mostly fire-and-forget) operations. It is up to you to implement corresponding error events to regular events from your IPC.

This gives you two options:
1. Just send a separate event on a different channel. If you encounter an error in your main thread, you can send an error event to an _error channel_ through the IPC. The renderer should then be wired up with an error action creator. Example:

### main
```js
...
sequelize(...)
  .then((content) => {
    win.webContents.send('pong', content)
  })
  .catch((error) => {
    win.webContents.send('pong:error', error)
  });
...
```

Note: `win.webContents.send` could be `event.sender.send` depending on if you are sending it to a window or replying to an IPC event. 

### renderer
```js
const ipc = createIpc({
  'pong': pongActionCreator, // on success
  'pong:error': pongErrActionCreate // on error
  ...
});
```

2. Implement a node-like callback style for your events by sending the error first or null and then the content. Example:

### main
```js
...
sequelize(...)
  .then((content) => {
    win.webContents.send('pong', null, content);
  })
  .catch((error) => {
    win.webContents.send('pong', error);
  });
...
```

### renderer
```js
const pongActionCreator = (event, error, content) => {
  if (error) {
    return {
      type: 'YOUR_FAILURE_REDUX_ACTION',
      error
    }
  }

  return {
    type: 'YOUR_SUCCESS_REDUX_ACTION',
    content
  }
};

const ipc = createIpc({
  'pong': pongActionCreator
  ...
});
```

Personally, I would go with option 1 to keep the events separate from one another. You will have to implement both action creators anyway on the renderer. Why not just hook them up separately (option 1)?

**Comment by mtompkins** [comment]
Perfect, thanks so much. This was what I was musing in my head but wanted to ask your opinion first. Much appreciated.

**Comment by mariotacke** [comment]
I _just_ updated the second example to simplify it a bit. I'd still favor option 1 though. Feel free to close the ticket if you had all your questions answered! Thanks for using my lib :)
