### ISSUE TITLE
Cannot find module "fs"

### ISSUE THREAD

**Issue by mim-Armand** [mariotacke/redux-electron-ipc#8]
When I try to import the package I get the missing module error:
``` javascript
// import createIpc from 'redux-electron-ipc' ==>
index.js:1 Uncaught Error: Cannot find module "fs"
    at webpackMissingModule (index.js:1)
    at Object.<anonymous> (index.js:1)
    at Object.../node_modules/electron/index.js (index.js:10)
    at __webpack_require__ (bootstrap 71970727b40f1c04444e:693)
    at fn (bootstrap 71970727b40f1c04444e:114)
    at webpackUniversalModuleDefinition (electron-redux-ipc.js:3)
    at Object../node_modules/redux-electron-ipc/dist/electron-redux-ipc.js (electron-redux-ipc.js:10)
    at __webpack_require__ (bootstrap 71970727b40f1c04444e:693)
    at fn (bootstrap 71970727b40f1c04444e:114)
    at Object../node_modules/redux-electron-ipc/index.js (index.js:1)
```
I think it's problem is with the CommonJS require here `module.exports = require('./dist/electron-redux-ipc.js');`, could be my webpack configs but it happens only whith this package so I thought I'd let you know.
👍

**Comment by mim-Armand** [comment]
Actually it may be when you import `ipcRenderer` from `electron`,
Webpack can't import that in my react side of the project, but it works fine when imported in a script tag in the shell HTML file that contains react and only when runs inside electron.. ( as comonjs is available there but not in the html )

**Comment by mariotacke** [comment]
Hi. Are you targeting `electron-renderer` in your webpack config ([docs](https://webpack.js.org/configuration/target/))? You should never have to require `ipcRenderer` outside of the middleware. Which version of webpack are you using?

**Comment by mim-Armand** [comment]
Hi @mariotacke, Thanks for your response,

I'm not using the `require(ipcRender)` outside of the middleware, it's complaining about it when happens in the `redux-electron-ipc` package,

My webpack version is `^2.5.1`, I am using **Redux-Cli** which uses **Redux Starter Kit** which has a [complicated webpack gonfig](https://github.com/davezuko/react-redux-starter-kit/blob/master/build/webpack.config.js), there were no target specified originally but when I had this issue, I tried to add `target: "electron-renderer"` after line 28 but that didn't change anything,

Looked more into it and I think this may be related to this issue:
https://github.com/electron/electron/issues/1611

**Comment by mariotacke** [comment]
This library was transpiled with webpack v1 targeting `electron`. Can you try to target `electron` over `electron-renderer`? I will have to set up a new webpack harness for v2/v3 webpack but it should not make a difference since its a umd library. The middleware does not require `fs` anywhere. For it to work, it needs access to `ipcRenderer` which should come with the `electron` target. Let me know how that goes.

**Comment by mim-Armand** [comment]
the middleware package is requiring `electron` and electron requires `fs`
targeting `electron` breaks the bundle, ( I guess it may be because I'm using >ES6 or something, it's complaining about some of the ES6-5 stuff like `exports` being undefined ).
I'll update you if I figured something out, thanks

**Comment by mim-Armand** [comment]
Hey @mariotacke, I tried a few things but no luck so far, even tried other packages,.. I think this may be my webpack config or a version incompatibility, I descided to just keep the communication logic in different places between the main and renderer and redux! and do it manually ( the messy way!) for now, if worked I may clean it up and share. just wanted to let you know that you can close this issue if you prefer to, thanks :+1:

**Comment by mariotacke** [comment]
Hey thanks for getting back to me on this. If you come across a solution, please add it here. If you have a bare bones repo where you can replicate this issue, i'd love to see it. Go ahead and close this issue if you are okay for now.
